version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: db_crud_angular
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_angular
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3307:3306'
